on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '12 9 * * 4'

jobs:
  SCS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: |
          dotnet restore
          dotnet build
